name       : font-roboto-ttf
version    : '2.138'
release    : 5
source     :
    - https://github.com/google/roboto/releases/download/v2.138/roboto-unhinted.zip : 70f64c718510a601fbcf752aafe644314dacaeb85474dc689c89787c4a72a728
license    : Apache-2.0
component  : desktop.font
summary    : The Roboto family of fonts
description: |
    The Roboto family of fonts
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/roboto/
    install -dm644 $fontdir
    cp -R $workdir/*.ttf $fontdir
    chmod -R 00644 $installdir
