name       : font-roboto-ttf
version    : 2.136
release    : 4
source     :
    - https://github.com/google/roboto/releases/download/v2.136/roboto-hinted.zip : c4528791de55ade3d6c698738a70b457311e4dd296c5a3318aa729874067fa6a
license    : Apache-2.0
component  : desktop.font
summary    : The Roboto family of fonts
description: |
    The Roboto family of fonts
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/roboto/
    install -dm644 $fontdir
    cp -R $workdir/*.ttf $fontdir
    chmod -R 00644 $installdir
